### create product
POST {{host}}/products
Content-Type: application/json

{
  "name": "any_name",
  "value": 10
}

### list products

GET {{host}}/products

### get product by id
GET {{host}}/products/{{productId}}

### update product by id
PUT {{host}}/products/{{productId}}
Content-Type: application/json

{
  "name": "updated_name",
  "value": 20
}

### delete product by id
DELETE {{host}}/products/{{productId}}

